name: flutter_uis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  # sdk: '>=2.12.0-135.0.dev <3.0.0'

dependency_overrides:
  path: 1.8.2
  intl: 0.17.0

  xml: 6.2.0
  petitparser: 5.1.0
  collection: 1.17.0

flutter_icons:
  includes:
    - fea
    - mco
    - ent
    - faw5s

analyzer:
  - enable-experiment:
      - non-nullable

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # Firebase
  firebase_core: 2.27.2
  firebase_analytics: 10.9.0
  firebase_messaging: 14.7.21
  firebase_crashlytics: 3.4.20
  firebase_performance: 0.9.3+19

  share: 2.0.4
  hive: 2.2.3
  open_url: 2.0.1
  hive_flutter: 1.1.0
  url_launcher: 6.2.5
  google_mobile_ads: 5.0.0
  package_info_plus: 6.0.0

  faker: 2.1.0
  emojis: 0.9.9
  recase: 4.1.0
  quiver: 3.2.1
  pigment: 1.0.4
  provider: 6.1.2
  riverpod: 2.5.1
  tinycolor2: 3.0.1
  supercharged: 2.1.1
  dotted_border: 2.1.0
  stretchy_header: 2.0.0
  page_transition: 2.1.0
  carousel_slider: 4.2.1
  flutter_riverpod: 2.5.1
  touchable_opacity: 1.2.0
  percent_indicator: 4.2.3
  simple_animations: 5.0.2
  flutter_font_icons: 2.2.7
  cupertino_will_pop_scope: 1.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  io: 1.0.3
  glob: 2.1.2
  yaml: 3.1.1
  translator: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/

    - assets/user/
    - assets/food/
    - assets/thumbnails/

    - assets/ma-hfd/
    - assets/ma-skv/
    - assets/ma-hab/
    - assets/ma-asc/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Muli
      fonts:
        - asset: fonts/Muli/Muli-ExtraLight.ttf
          weight: 200
        - asset: fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: fonts/Muli/Muli-Regular.ttf
          weight: 400
        - asset: fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: fonts/Muli/Muli-ExtraBold.ttf
          weight: 800
        - asset: fonts/Muli/Muli-Black.ttf
          weight: 900

    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue/BebasNeue-Regular.ttf
          weight: 400
