name: flutter_uis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  device_info: 0.4.0+3

  firebase_core: 0.4.4
  firebase_analytics: 5.0.11
  firebase_performance: 0.3.1+5
  firebase_crashlytics: 0.1.2+5

  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.6.0

  url_launcher: ^5.4.1
  universal_io: ^0.8.6

  flash: ^1.1.0
  pigment: ^1.0.3
  cupertino_icons: ^0.1.3
  flutter_vector_icons: ^0.2.1
  simple_animations: ^1.3.6
  carousel_slider: ^1.4.1
  percent_indicator: ^2.1.1+1
  flutter_device_type: ^0.2.0

  color: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user/cover.jpg
    - assets/user/hamza.jpg

    - assets/thumbnails/healthy_food_delivery.png
    - assets/ma-hfd/item-1.jpg
    - assets/ma-hfd/item-2.jpg
    - assets/ma-hfd/item-3.jpg
    - assets/ma-hfd/item-4.jpg
    - assets/ma-hfd/item-5.jpg
    - assets/ma-hfd/item-6.jpg
    - assets/ma-hfd/item-7.jpg
    - assets/ma-hfd/item-8.jpg
    - assets/ma-hfd/item-9.jpg
    - assets/ma-hfd/resturant-1.jpg
    - assets/ma-hfd/resturant-2.jpg
    - assets/ma-hfd/resturant-3.jpg
    - assets/ma-hfd/resturant-4.jpg
    - assets/ma-hfd/resturant-5.jpg

    - assets/thumbnails/hot_air_balloon.jpg
    - assets/ma-hab/bubbles-bg.png
    - assets/ma-hab/balloon.png
    - assets/ma-hab/balloon-shadow.png
    - assets/ma-hab/mountains.jpg

    - assets/thumbnails/sky_view.jpg
    - assets/ma-sk/mars-planet.png
    - assets/ma-sk/venus-planet.png
    - assets/ma-sk/andromeda.png
    - assets/ma-sk/hubble-space-telescope.png
    - assets/ma-sk/international-space-station.png
    - assets/ma-sk/stars-bg.jpg
    - assets/ma-sk/gradient-path.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Muli
      fonts:
        - asset: fonts/Muli/Muli-ExtraLight.ttf
          weight: 200
        - asset: fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: fonts/Muli/Muli-Regular.ttf
          weight: 400
        - asset: fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: fonts/Muli/Muli-ExtraBold.ttf
          weight: 800
        - asset: fonts/Muli/Muli-Black.ttf
          weight: 900
